srid/rib

rib.cabal, src/Rib/Settings.hs, src/Rib/Shake.hs
Much simpler than the default backward-defined system.
Closes #15
=> Switch to Development.Shake.Forward

README.md, default.nix, examples/doc/a/inbox.md, examples/doc/default.nix, examples/doc/doc.cabal, examples/hello-world/default.nix, examples/hello-world/hello-world.cabal, examples/invoice-generator/default.nix, examples/invoice-generator/invoice-generator.cabal, ghcid, rib.cabal, src/Rib/App.hs
=> Make examples independent cabal projects

CHANGELOG.md, rib.cabal, src/Rib/App.hs, src/Rib/Markup.hs, src/Rib/Markup/MMark.hs, src/Rib/Markup/Pandoc.hs, src/Rib/Server.hs, src/Rib/Shake.hs
http://hackage.haskell.org/package/path
=> Use type-safe paths

src/Rib.hs, src/Rib/App.hs, src/Rib/Markup.hs, src/Rib/Markup/MMark.hs, src/Rib/Markup/Pandoc.hs, src/Rib/Server.hs, src/Rib/Shake.hs
https://www.reddit.com/r/haskell/comments/btmb30/tweag_io_ormolu_format_haskell_code_like_never/
=> Re-format source tree using ormolu

.github/workflows/ci.yaml, default.nix
=> Add macOS to CI matrix

src/Rib/Shake.hs
`buildHtml` was incorrectly named; it should have actually been called
`writeHtml`. This commit also actually implements `buildHtml`, which is like
`buildHtmlMulti` but operating on a single file.
Here's an example demonstrating all these functions, taken from https://github.com/srid/website/pull/6
```haskell
main = Rib.run [reldir|a|] [reldir|c|] $ do
Rib.buildStaticFiles [[relfile|static/**|]]
void $ Rib.buildHtml [relfile|tidbits.dhall|] Tidbit.parse $ renderPage . Page_Tidbits
posts <- Rib.buildHtmlMulti [[relfile|*.md|]] MMark.parse $ renderPage . Page_Individual
blurb <- Rib.readSource MMark.parse [relfile|fragments/index.md|]
Rib.writeHtml [relfile|index.html|] $ renderPage (Page_Index blurb posts)
```
=> Add singular version of buildHtmlMulti

src/Rib/Parser/Pandoc.hs
Just have the user pass around one of the pandoc reader
functions (re-exported in Rib.Parser.Pandoc) directly instead of having
to know to use a custom wrapper type.
Fixes #54
=> Remove PandocFormat; directly use pandoc readers

src/Rib/Shake.hs, src/Rib/Source.hs
Consequently readSource returns repr directly.
Fixes #78
=> Have buildHtml set sourceUrl

CHANGELOG.md, default.nix, rib.cabal, src/Rib.hs, src/Rib/Parser/Dhall.hs
=> Add Rib.Parser.Dhall

CHANGELOG.md, src/Rib/Parser/MMark.hs
So the user can specify a custom list of extensions.
Closes #89
=> Add MMark.parseWith

CHANGELOG.md, rib.cabal, src/Rib/App.hs
And expose `commandParser` in API.
Closes #80
=> Switch to optparse-applicative

README.md
Also replace builtwithnix logo for style consistency
=> Add zulip-archive to examples

CHANGELOG.md, src/Rib/Extra/CSS.hs, src/Rib/Parser/Pandoc.hs
Closes #52
Maybe add to rib-sample.
=> Add getToC for Pandoc

CHANGELOG.md, src/Rib/Parser/MMark.hs
Useful to automatically determine OpenGraph description.
=> Add `Rib.Parser.MMark.getFirstParagraphText`

src/Rib/Parser/Pandoc.hs
=> [#122] Fix pandoc metadata parsing

CHANGELOG.md, README.md, src/Rib/Server.hs
cf. https://github.com/srid/neuron/issues/19
=> Run HTTP server at 127.0.0.1

CHANGELOG.md, rib.cabal, src/Rib/App.hs, src/Rib/Watch.hs
=> Put .shake under `ribInputDir`

rib.cabal, src/Rib/App.hs, src/Rib/Settings.hs, src/Rib/Shake.hs
For quite running of a Shake command. This is more of a temporary hack, until properly logging gets implemented.
=> Add OneOff command

.github/workflows/ci.yaml, CHANGELOG.md, bin/test, rib.cabal, src/Rib/App.hs, src/Rib/Cli.hs, src/Rib/Server.hs, test/Rib/CliSpec.hs, test/Spec.hs
=> Allow specifying (optional) host along with port

README.md
=> Add Shake link
